GET http://localhost:5001/admin-dashboard/listings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWQxOGJhOGU4OTU5M2IzZmM1YzJiZjEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDk0MTQ3NDMsImV4cCI6MTcwOTQxODM0M30.wpBc5d11Q1tWKMmTQf5hlQOobTbSg4wAZWVcAlbYgF8

# POST http://localhost:5001/bookings
# Content-Type: application/json

# {
#     "vehicleId": "6526dc233acee4d5f5b21c4d", 
#     "userId": "65d18b8ce89593b3fc5c2bed",  
#     "totalAmount": "300",      
#     "status": "Pending",  
#     "createdBy": "65d18ba8e89593b3fc5c2bf1"                       
# }


