
### To Get All
GET http://localhost:5001/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWQxOGI4Y2U4OTU5M2IzZmM1YzJiZWQiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxMTMwODg3NiwiZXhwIjoxNzExMzEyNDc2fQ.BoBU6r655WmPiVUDdN_vtS9a9VzaoJhxw10P78rbzkA

### To Get One
GET http://localhost:5001/vehicles/65e687262af9f2e025c89f7b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWQxOGI4Y2U4OTU5M2IzZmM1YzJiZWQiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxMTMxMjU2NSwiZXhwIjoxNzExMzE2MTY1fQ.arE0BvI336bxTx1SJ3hITvW7pfXDte4P3jdm1Nux268


### To add vehicle
POST http://localhost:5001/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWQxOGJhOGU4OTU5M2IzZmM1YzJiZjEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDg5OTcyOTEsImV4cCI6MTcwOTAwMDg5MX0.51LKF-rJgqa5RqLXF7GeyU3Ljnqf7gyUc2dMMSXNftU

{
   "vehicleType": "boat",
    "make": "MasterCraft",
    "model": "X-Star",
    "year": 2022,
    "image": "url/to/boat-image.jpg",
    "capacity": 8,
    "fuelType": "Gasoline",
    "bookedTimeSlots": [],
    "availability": true,
    "rentPerHour": 89.99,
    "description": "",
    "reviews": [],
    "createdBy":"65d18ba8e89593b3fc5c2bf1"
}


### To delete
DELETE http://localhost:5001/vehicles/6526ec9cd7562b897a11ca4e


### To update
PATCH http://localhost:5001/vehicles/6526ec9cd7562b897a11ca4e
Content-Type: application/json

{
    "image": "https://pngimg.com/d/mercedes_PNG80175.png"
}
